version: "3.9"

services:
  DotNetflixStorage:
    image: aspnetdotnetflixstorage
    container_name: dotnetflixstorage
    ports:
      - "7126:80"
    build:
      context: ./DotNetflixServer/
      dockerfile: DockerfileDotnetflixStorage
    depends_on:
      - MinioS3
      - RabbitMq
    environment:
      - MinioS3__AccessKey=minioadmin
      - MinioS3__SecretKey=minioadmin
      - MinioS3__Timeout=5000
      - MinioS3__Endpoint=minio:9000
      - RabbitMqConfig__Username=admin
      - RabbitMqConfig__Password=admin
      - RabbitMqConfig__Hostname=RabbitMq
      - RabbitMqConfig__Port=5672
      - ConnectionStrings__Redis=storageRedis:6379,password=${StorageRedisPassword}
  RedisAuth:
    container_name: storageRedis
    image: redis:7.2.3-alpine3.18
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass ${StorageRedisPassword}
  MinioS3:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address ":9001" /data/
  RabbitMq:
    image: rabbitmq:3-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
  SupportChat:
    image: aspnetdotnetflixsupportchat
    container_name: dotnetflixsupportchat
    ports:
      - "7280:80"
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=mssql;Initial Catalog=DotNetflixDB;User=sa;Password=pmwPmN1Hgh0SDd2f1TfX!;Connect Timeout=300;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False
      - RabbitMqConfig__Username=admin
      - RabbitMqConfig__Password=admin
      - RabbitMqConfig__Hostname=RabbitMq
      - RabbitMqConfig__Port=5672
      - SAPassword=pmwPmN1Hgh0SDd2f1TfX!
    build:
      context: ./DotNetflixServer
      dockerfile: DockerfileSupportChat
    depends_on:
      - mssql
      - RabbitMq
  DotNetflixAPI:
    image: aspnetdotnetflixapi
    container_name: dotnetflixserver
    ports:
      - "7289:443"
    environment:
      - RabbitMqConfig__Username=admin
      - RabbitMqConfig__Password=admin
      - RabbitMqConfig__Hostname=RabbitMq
      - RabbitMqConfig__Port=5672
      - FrontendBaseUrl=http://localhost:3000
      - SAPassword=pmwPmN1Hgh0SDd2f1TfX!
      - MinioApiBaseUrl=http://dotnetflixs3
      - SmtpSetting__FromPassword=gomlmldthveiefjr
      - ConnectionStrings__DefaultConnection=Data Source=mssql;Initial Catalog=DotNetflixDB;User=sa;Password=pmwPmN1Hgh0SDd2f1TfX!;Connect Timeout=300;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False
      - OAuth__ApiOAuth=http://localhost:7289/api/oauth/google
      - GoogleOAuth:ClientId=${GoogleOAuthClientId}
      - GoogleOAuth:ClientSecret=${GoogleOAuthClientSecret}
      - ASPNETCORE_ENVIRONMENT:Production
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${KestrelCertifPass}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    build:
      context: ./DotNetflixServer
      dockerfile: DockerfileDotNetflixAPI
    depends_on:
      - mssql
      - DotNetflixAdminAPI
      - RabbitMq
  DotNetflixAdminAPI:
    image: aspnetdotdetflixadminapi
    container_name: dotnetflixserveradmin
    ports:
      - "7298:443"
    environment:
      - SAPassword=pmwPmN1Hgh0SDd2f1TfX!
      - MinioApiBaseUrl=http://dotnetflixs3
      - SmtpSetting__FromPassword=gomlmldthveiefjr
      - ConnectionStrings__DefaultConnection=Data Source=mssql;Initial Catalog=DotNetflixDB;User=sa;Password=pmwPmN1Hgh0SDd2f1TfX!;Connect Timeout=300;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False
      - ASPNETCORE_ENVIRONMENT:Production
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${KestrelCertifPass}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    build:
      context: ./DotNetflixServer
      dockerfile: DockerfileDotNetflixAdminAPI
    depends_on:
      - mssql
  DotNetflixAPIClient:
    image: dotnetflixapiclient
    container_name: dotnetflixserverclient
    ports:
      - "3000:3000"
    build:
      context: ./DotNetflixClient
      dockerfile: Dockerfile
    depends_on:
      - DotNetflixAPI
  DotNetflixAPIClientAdmin:
    image: dotnetflixadminapiclient
    container_name: dotnetflixserveradminclient
    ports:
      - "3001:3001"
    build:
      context: ./DotNetflixAdmin
      dockerfile: Dockerfile
    depends_on:
      - DotNetflixAdminAPI
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1414:1433"
    volumes:
      - ~/apps/mssql/data:/var/lib/mssqlql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=pmwPmN1Hgh0SDd2f1TfX!
  