name: mobile
description: ".NETflix mobile"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  graphql_flutter: ^5.1.2
  intl: ^0.19.0
  provider: ^6.1.2
  flag: ^7.0.0
  flutter_guid: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/dotnetflix-bgi.jpg
