name: mobile
description: ".NETflix mobile"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  graphql_flutter: ^5.1.2
  intl: ^0.19.0
  provider: ^6.1.2
  flag: ^7.0.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  http: ^1.2.1
  flutter_guid: ^0.3.1
  flutter_secure_storage: ^9.0.0
  protobuf: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

  assets:
    - assets/dotnetflix-bgi.jpg
