apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-depl
  labels:
    app: mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2022-latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "pmwPmN1Hgh0SDd2f1TfX!"
          ports:
            - containerPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-srv
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer
  