// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20230405055620_AddEnumsData")]
    partial class AddEnumsData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.2.23128.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Entities.BusinessLogic.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Новинки"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Топ-10 лучших фильмов"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Топ-10 лучших российских фильмов"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Топ-10 лучших сериалов"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Выбор редакции"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Группа 11-106 рекомендует"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Киновселенная Marvel"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Непревзойдённый Райан Гослинг"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.BusinessLogic.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Австралия",
                            Slug = "Avstraliya"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Австрия",
                            Slug = "Avstriya"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Азербайджан",
                            Slug = "Azerbaydzhan"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Албания",
                            Slug = "Albaniya"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Алжир",
                            Slug = "Alzhir"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Американские Виргинские острова",
                            Slug = "Amerikanskie-Virginskie-ostrova"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Американское Самоа",
                            Slug = "Amerikanskoe-Samoa"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Ангола",
                            Slug = "Angola"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Андорра",
                            Slug = "Andorra"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Антарктида",
                            Slug = "Antarktida"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Антигуа и Барбуда",
                            Slug = "Antigua-i-Barbuda"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Антильские Острова",
                            Slug = "Antilskie-Ostrova"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Аргентина",
                            Slug = "Argentina"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Армения",
                            Slug = "Armeniya"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Аруба",
                            Slug = "Aruba"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Афганистан",
                            Slug = "Afganistan"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Багамы",
                            Slug = "Bagamy"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Бангладеш",
                            Slug = "Bangladesh"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Барбадос",
                            Slug = "Barbados"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Бахрейн",
                            Slug = "Bahreyn"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Беларусь",
                            Slug = "Belarus"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Белиз",
                            Slug = "Beliz"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Бельгия",
                            Slug = "Belgiya"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Бенин",
                            Slug = "Benin"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Берег Слоновой кости",
                            Slug = "Bereg-Slonovoy-kosti"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Бермуды",
                            Slug = "Bermudy"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Бирма",
                            Slug = "Birma"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Болгария",
                            Slug = "Bolgariya"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Боливия",
                            Slug = "Boliviya"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Босния",
                            Slug = "Bosniya"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Босния и Герцеговина",
                            Slug = "Bosniya-i-Gercegovina"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Ботсвана",
                            Slug = "Botsvana"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Бразилия",
                            Slug = "Braziliya"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Бруней-Даруссалам",
                            Slug = "Bruney-Darussalam"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Буркина-Фасо",
                            Slug = "Burkina-Faso"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Бурунди",
                            Slug = "Burundi"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Бутан",
                            Slug = "Butan"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Вануату",
                            Slug = "Vanuatu"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Ватикан",
                            Slug = "Vatikan"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Великобритания",
                            Slug = "Velikobritaniya"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Венгрия",
                            Slug = "Vengriya"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Венесуэла",
                            Slug = "Venesuela"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Виргинские Острова",
                            Slug = "Virginskie-Ostrova"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Внешние малые острова США",
                            Slug = "Vneshnie-malye-ostrova-SShA"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Вьетнам",
                            Slug = "Vetnam"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Вьетнам Северный",
                            Slug = "Vetnam-Severnyy"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Габон",
                            Slug = "Gabon"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Гаити",
                            Slug = "Gaiti"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Гайана",
                            Slug = "Gayana"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Гамбия",
                            Slug = "Gambiya"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Гана",
                            Slug = "Gana"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Гваделупа",
                            Slug = "Gvadelupa"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Гватемала",
                            Slug = "Gvatemala"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Гвинея",
                            Slug = "Gvineya"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Гвинея-Бисау",
                            Slug = "Gvineya-Bisau"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Германия",
                            Slug = "Germaniya"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Германия (ГДР)",
                            Slug = "Germaniya-(GDR)"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Германия (ФРГ)",
                            Slug = "Germaniya-(FRG)"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Гибралтар",
                            Slug = "Gibraltar"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Гондурас",
                            Slug = "Gonduras"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Гонконг",
                            Slug = "Gonkong"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Гренада",
                            Slug = "Grenada"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Гренландия",
                            Slug = "Grenlandiya"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Греция",
                            Slug = "Greciya"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Грузия",
                            Slug = "Gruziya"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Гуам",
                            Slug = "Guam"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Дания",
                            Slug = "Daniya"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Джибути",
                            Slug = "Dzhibuti"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Доминика",
                            Slug = "Dominika"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Доминикана",
                            Slug = "Dominikana"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Египет",
                            Slug = "Egipet"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Заир",
                            Slug = "Zair"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Замбия",
                            Slug = "Zambiya"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Западная Сахара",
                            Slug = "Zapadnaya-Sahara"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Зимбабве",
                            Slug = "Zimbabve"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Израиль",
                            Slug = "Izrail"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Индия",
                            Slug = "Indiya"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Индонезия",
                            Slug = "Indoneziya"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Иордания",
                            Slug = "Iordaniya"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Ирак",
                            Slug = "Irak"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Иран",
                            Slug = "Iran"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Ирландия",
                            Slug = "Irlandiya"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Исландия",
                            Slug = "Islandiya"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Испания",
                            Slug = "Ispaniya"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Италия",
                            Slug = "Italiya"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Йемен",
                            Slug = "Yemen"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Кабо-Верде",
                            Slug = "Kabo-Verde"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Казахстан",
                            Slug = "Kazahstan"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Каймановы острова",
                            Slug = "Kaymanovy-ostrova"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Камбоджа",
                            Slug = "Kambodzha"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Камерун",
                            Slug = "Kamerun"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Канада",
                            Slug = "Kanada"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Катар",
                            Slug = "Katar"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Кения",
                            Slug = "Keniya"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Кипр",
                            Slug = "Kipr"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Киргизия",
                            Slug = "Kirgiziya"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Кирибати",
                            Slug = "Kiribati"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Китай",
                            Slug = "Kitay"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Колумбия",
                            Slug = "Kolumbiya"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Коморы",
                            Slug = "Komory"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Конго",
                            Slug = "Kongo"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Конго (ДРК)",
                            Slug = "Kongo-(DRK)"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Корея",
                            Slug = "Koreya"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Корея Северная",
                            Slug = "Koreya-Severnaya"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Корея Южная",
                            Slug = "Koreya-Yuzhnaya"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Косово",
                            Slug = "Kosovo"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Коста-Рика",
                            Slug = "Kosta-Rika"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Кот-д’Ивуар",
                            Slug = "Kot-d'Ivuar"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Куба",
                            Slug = "Kuba"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Кувейт",
                            Slug = "Kuveyt"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Лаос",
                            Slug = "Laos"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Латвия",
                            Slug = "Latviya"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Лесото",
                            Slug = "Lesoto"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Либерия",
                            Slug = "Liberiya"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Ливан",
                            Slug = "Livan"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Ливия",
                            Slug = "Liviya"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Литва",
                            Slug = "Litva"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Лихтенштейн",
                            Slug = "Lihtenshteyn"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Люксембург",
                            Slug = "Lyuksemburg"
                        },
                        new
                        {
                            Id = 120,
                            Name = "Маврикий",
                            Slug = "Mavrikiy"
                        },
                        new
                        {
                            Id = 121,
                            Name = "Мавритания",
                            Slug = "Mavritaniya"
                        },
                        new
                        {
                            Id = 122,
                            Name = "Мадагаскар",
                            Slug = "Madagaskar"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Макао",
                            Slug = "Makao"
                        },
                        new
                        {
                            Id = 124,
                            Name = "Македония",
                            Slug = "Makedoniya"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Малави",
                            Slug = "Malavi"
                        },
                        new
                        {
                            Id = 126,
                            Name = "Малайзия",
                            Slug = "Malayziya"
                        },
                        new
                        {
                            Id = 127,
                            Name = "Мали",
                            Slug = "Mali"
                        },
                        new
                        {
                            Id = 128,
                            Name = "Мальдивы",
                            Slug = "Maldivy"
                        },
                        new
                        {
                            Id = 129,
                            Name = "Мальта",
                            Slug = "Malta"
                        },
                        new
                        {
                            Id = 130,
                            Name = "Марокко",
                            Slug = "Marokko"
                        },
                        new
                        {
                            Id = 131,
                            Name = "Мартиника",
                            Slug = "Martinika"
                        },
                        new
                        {
                            Id = 132,
                            Name = "Маршалловы острова",
                            Slug = "Marshallovy-ostrova"
                        },
                        new
                        {
                            Id = 133,
                            Name = "Мексика",
                            Slug = "Meksika"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Мозамбик",
                            Slug = "Mozambik"
                        },
                        new
                        {
                            Id = 135,
                            Name = "Молдова",
                            Slug = "Moldova"
                        },
                        new
                        {
                            Id = 136,
                            Name = "Монако",
                            Slug = "Monako"
                        },
                        new
                        {
                            Id = 137,
                            Name = "Монголия",
                            Slug = "Mongoliya"
                        },
                        new
                        {
                            Id = 138,
                            Name = "Монтсеррат",
                            Slug = "Montserrat"
                        },
                        new
                        {
                            Id = 139,
                            Name = "Мьянма",
                            Slug = "Myanma"
                        },
                        new
                        {
                            Id = 140,
                            Name = "Намибия",
                            Slug = "Namibiya"
                        },
                        new
                        {
                            Id = 141,
                            Name = "Непал",
                            Slug = "Nepal"
                        },
                        new
                        {
                            Id = 142,
                            Name = "Нигер",
                            Slug = "Niger"
                        },
                        new
                        {
                            Id = 143,
                            Name = "Нигерия",
                            Slug = "Nigeriya"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Нидерланды",
                            Slug = "Niderlandy"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Никарагуа",
                            Slug = "Nikaragua"
                        },
                        new
                        {
                            Id = 146,
                            Name = "Новая Зеландия",
                            Slug = "Novaya-Zelandiya"
                        },
                        new
                        {
                            Id = 147,
                            Name = "Новая Каледония",
                            Slug = "Novaya-Kaledoniya"
                        },
                        new
                        {
                            Id = 148,
                            Name = "Норвегия",
                            Slug = "Norvegiya"
                        },
                        new
                        {
                            Id = 149,
                            Name = "ОАЭ",
                            Slug = "OAE"
                        },
                        new
                        {
                            Id = 150,
                            Name = "Оккупированная Палестинская территория",
                            Slug = "Okkupirovannaya-Palestinskaya-territoriya"
                        },
                        new
                        {
                            Id = 151,
                            Name = "Оман",
                            Slug = "Oman"
                        },
                        new
                        {
                            Id = 152,
                            Name = "Остров Мэн",
                            Slug = "Ostrov-Men"
                        },
                        new
                        {
                            Id = 153,
                            Name = "Острова Кука",
                            Slug = "Ostrova-Kuka"
                        },
                        new
                        {
                            Id = 154,
                            Name = "Пакистан",
                            Slug = "Pakistan"
                        },
                        new
                        {
                            Id = 155,
                            Name = "Палау",
                            Slug = "Palau"
                        },
                        new
                        {
                            Id = 156,
                            Name = "Палестина",
                            Slug = "Palestina"
                        },
                        new
                        {
                            Id = 157,
                            Name = "Панама",
                            Slug = "Panama"
                        },
                        new
                        {
                            Id = 158,
                            Name = "Папуа - Новая Гвинея",
                            Slug = "Papua---Novaya-Gvineya"
                        },
                        new
                        {
                            Id = 159,
                            Name = "Парагвай",
                            Slug = "Paragvay"
                        },
                        new
                        {
                            Id = 160,
                            Name = "Перу",
                            Slug = "Peru"
                        },
                        new
                        {
                            Id = 161,
                            Name = "Польша",
                            Slug = "Polsha"
                        },
                        new
                        {
                            Id = 162,
                            Name = "Португалия",
                            Slug = "Portugaliya"
                        },
                        new
                        {
                            Id = 163,
                            Name = "Пуэрто Рико",
                            Slug = "Puerto-Riko"
                        },
                        new
                        {
                            Id = 164,
                            Name = "Реюньон",
                            Slug = "Reyunon"
                        },
                        new
                        {
                            Id = 165,
                            Name = "Российская империя",
                            Slug = "Rossiyskaya-imperiya"
                        },
                        new
                        {
                            Id = 166,
                            Name = "Россия",
                            Slug = "Rossiya"
                        },
                        new
                        {
                            Id = 167,
                            Name = "Руанда",
                            Slug = "Ruanda"
                        },
                        new
                        {
                            Id = 168,
                            Name = "Румыния",
                            Slug = "Rumyniya"
                        },
                        new
                        {
                            Id = 169,
                            Name = "СССР",
                            Slug = "SSSR"
                        },
                        new
                        {
                            Id = 170,
                            Name = "США",
                            Slug = "SShA"
                        },
                        new
                        {
                            Id = 171,
                            Name = "Сальвадор",
                            Slug = "Salvador"
                        },
                        new
                        {
                            Id = 172,
                            Name = "Самоа",
                            Slug = "Samoa"
                        },
                        new
                        {
                            Id = 173,
                            Name = "Сан-Марино",
                            Slug = "San-Marino"
                        },
                        new
                        {
                            Id = 174,
                            Name = "Саудовская Аравия",
                            Slug = "Saudovskaya-Araviya"
                        },
                        new
                        {
                            Id = 175,
                            Name = "Свазиленд",
                            Slug = "Svazilend"
                        },
                        new
                        {
                            Id = 176,
                            Name = "Северная Македония",
                            Slug = "Severnaya-Makedoniya"
                        },
                        new
                        {
                            Id = 177,
                            Name = "Сейшельские острова",
                            Slug = "Seyshelskie-ostrova"
                        },
                        new
                        {
                            Id = 178,
                            Name = "Сенегал",
                            Slug = "Senegal"
                        },
                        new
                        {
                            Id = 179,
                            Name = "Сент-Винсент и Гренадины",
                            Slug = "Sent-Vinsent-i-Grenadiny"
                        },
                        new
                        {
                            Id = 180,
                            Name = "Сент-Китс и Невис",
                            Slug = "Sent-Kits-i-Nevis"
                        },
                        new
                        {
                            Id = 181,
                            Name = "Сент-Люсия ",
                            Slug = "Sent-Lyusiya-"
                        },
                        new
                        {
                            Id = 182,
                            Name = "Сербия",
                            Slug = "Serbiya"
                        },
                        new
                        {
                            Id = 183,
                            Name = "Сербия и Черногория",
                            Slug = "Serbiya-i-Chernogoriya"
                        },
                        new
                        {
                            Id = 184,
                            Name = "Сиам",
                            Slug = "Siam"
                        },
                        new
                        {
                            Id = 185,
                            Name = "Сингапур",
                            Slug = "Singapur"
                        },
                        new
                        {
                            Id = 186,
                            Name = "Сирия",
                            Slug = "Siriya"
                        },
                        new
                        {
                            Id = 187,
                            Name = "Словакия",
                            Slug = "Slovakiya"
                        },
                        new
                        {
                            Id = 188,
                            Name = "Словения",
                            Slug = "Sloveniya"
                        },
                        new
                        {
                            Id = 189,
                            Name = "Соломоновы Острова",
                            Slug = "Solomonovy-Ostrova"
                        },
                        new
                        {
                            Id = 190,
                            Name = "Сомали",
                            Slug = "Somali"
                        },
                        new
                        {
                            Id = 191,
                            Name = "Судан",
                            Slug = "Sudan"
                        },
                        new
                        {
                            Id = 192,
                            Name = "Суринам",
                            Slug = "Surinam"
                        },
                        new
                        {
                            Id = 193,
                            Name = "Сьерра-Леоне",
                            Slug = "Serra-Leone"
                        },
                        new
                        {
                            Id = 194,
                            Name = "Таджикистан",
                            Slug = "Tadzhikistan"
                        },
                        new
                        {
                            Id = 195,
                            Name = "Таиланд",
                            Slug = "Tailand"
                        },
                        new
                        {
                            Id = 196,
                            Name = "Тайвань",
                            Slug = "Tayvan"
                        },
                        new
                        {
                            Id = 197,
                            Name = "Танзания",
                            Slug = "Tanzaniya"
                        },
                        new
                        {
                            Id = 198,
                            Name = "Тимор-Лесте",
                            Slug = "Timor-Leste"
                        },
                        new
                        {
                            Id = 199,
                            Name = "Того",
                            Slug = "Togo"
                        },
                        new
                        {
                            Id = 200,
                            Name = "Тонга",
                            Slug = "Tonga"
                        },
                        new
                        {
                            Id = 201,
                            Name = "Тринидад и Тобаго",
                            Slug = "Trinidad-i-Tobago"
                        },
                        new
                        {
                            Id = 202,
                            Name = "Тувалу",
                            Slug = "Tuvalu"
                        },
                        new
                        {
                            Id = 203,
                            Name = "Тунис",
                            Slug = "Tunis"
                        },
                        new
                        {
                            Id = 204,
                            Name = "Туркменистан",
                            Slug = "Turkmenistan"
                        },
                        new
                        {
                            Id = 205,
                            Name = "Турция",
                            Slug = "Turciya"
                        },
                        new
                        {
                            Id = 206,
                            Name = "Уганда",
                            Slug = "Uganda"
                        },
                        new
                        {
                            Id = 207,
                            Name = "Узбекистан",
                            Slug = "Uzbekistan"
                        },
                        new
                        {
                            Id = 208,
                            Name = "Украина",
                            Slug = "Ukraina"
                        },
                        new
                        {
                            Id = 209,
                            Name = "Уоллис и Футуна",
                            Slug = "Uollis-i-Futuna"
                        },
                        new
                        {
                            Id = 210,
                            Name = "Уругвай",
                            Slug = "Urugvay"
                        },
                        new
                        {
                            Id = 211,
                            Name = "Фарерские острова",
                            Slug = "Farerskie-ostrova"
                        },
                        new
                        {
                            Id = 212,
                            Name = "Федеративные Штаты Микронезии",
                            Slug = "Federativnye-Shtaty-Mikronezii"
                        },
                        new
                        {
                            Id = 213,
                            Name = "Фиджи",
                            Slug = "Fidzhi"
                        },
                        new
                        {
                            Id = 214,
                            Name = "Филиппины",
                            Slug = "Filippiny"
                        },
                        new
                        {
                            Id = 215,
                            Name = "Финляндия",
                            Slug = "Finlyandiya"
                        },
                        new
                        {
                            Id = 216,
                            Name = "Фолклендские острова",
                            Slug = "Folklendskie-ostrova"
                        },
                        new
                        {
                            Id = 217,
                            Name = "Франция",
                            Slug = "Franciya"
                        },
                        new
                        {
                            Id = 218,
                            Name = "Французская Гвиана",
                            Slug = "Francuzskaya-Gviana"
                        },
                        new
                        {
                            Id = 219,
                            Name = "Французская Полинезия",
                            Slug = "Francuzskaya-Polineziya"
                        },
                        new
                        {
                            Id = 220,
                            Name = "Хорватия",
                            Slug = "Horvatiya"
                        },
                        new
                        {
                            Id = 221,
                            Name = "ЦАР",
                            Slug = "CAR"
                        },
                        new
                        {
                            Id = 222,
                            Name = "Чад",
                            Slug = "Chad"
                        },
                        new
                        {
                            Id = 223,
                            Name = "Черногория",
                            Slug = "Chernogoriya"
                        },
                        new
                        {
                            Id = 224,
                            Name = "Чехия",
                            Slug = "Chehiya"
                        },
                        new
                        {
                            Id = 225,
                            Name = "Чехословакия",
                            Slug = "Chehoslovakiya"
                        },
                        new
                        {
                            Id = 226,
                            Name = "Чили",
                            Slug = "Chili"
                        },
                        new
                        {
                            Id = 227,
                            Name = "Швейцария",
                            Slug = "Shveycariya"
                        },
                        new
                        {
                            Id = 228,
                            Name = "Швеция",
                            Slug = "Shveciya"
                        },
                        new
                        {
                            Id = 229,
                            Name = "Шри-Ланка",
                            Slug = "Shri-Lanka"
                        },
                        new
                        {
                            Id = 230,
                            Name = "Эквадор",
                            Slug = "Ekvador"
                        },
                        new
                        {
                            Id = 231,
                            Name = "Экваториальная Гвинея",
                            Slug = "Ekvatorialnaya-Gvineya"
                        },
                        new
                        {
                            Id = 232,
                            Name = "Эритрея",
                            Slug = "Eritreya"
                        },
                        new
                        {
                            Id = 233,
                            Name = "Эстония",
                            Slug = "Estoniya"
                        },
                        new
                        {
                            Id = 234,
                            Name = "Эфиопия",
                            Slug = "Efiopiya"
                        },
                        new
                        {
                            Id = 235,
                            Name = "ЮАР",
                            Slug = "YuAR"
                        },
                        new
                        {
                            Id = 236,
                            Name = "Югославия",
                            Slug = "Yugoslaviya"
                        },
                        new
                        {
                            Id = 237,
                            Name = "Югославия (ФР)",
                            Slug = "Yugoslaviya-(FR)"
                        },
                        new
                        {
                            Id = 238,
                            Name = "Ямайка",
                            Slug = "Yamayka"
                        },
                        new
                        {
                            Id = 239,
                            Name = "Япония",
                            Slug = "Yaponiya"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.BusinessLogic.CountryMovieInfo", b =>
                {
                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("MovieInfoId")
                        .HasColumnType("int");

                    b.HasKey("CountryId", "MovieInfoId");

                    b.HasIndex("MovieInfoId");

                    b.ToTable("CountryMovieInfo");
                });

            modelBuilder.Entity("DataAccess.Entities.BusinessLogic.CurrencyValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Value")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("CurrencyValues", t =>
                        {
                            t.HasCheckConstraint("CK_CurrencyValue_Value", "Value >= 0");
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.BusinessLogic.Fees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("RussiaId")
                        .HasColumnType("int");

                    b.Property<int?>("USAId")
                        .HasColumnType("int");

                    b.Property<int?>("WorldId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RussiaId");

                    b.HasIndex("USAId");

                    b.HasIndex("WorldId");

                    b.ToTable("Fees");
                });

            modelBuilder.Entity("DataAccess.Entities.BusinessLogic.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "аниме",
                            Slug = "anime"
                        },
                        new
                        {
                            Id = 2,
                            Name = "биография",
                            Slug = "biografiya"
                        },
                        new
                        {
                            Id = 3,
                            Name = "боевик",
                            Slug = "boevik"
                        },
                        new
                        {
                            Id = 4,
                            Name = "вестерн",
                            Slug = "vestern"
                        },
                        new
                        {
                            Id = 5,
                            Name = "военный",
                            Slug = "voennyy"
                        },
                        new
                        {
                            Id = 6,
                            Name = "детектив",
                            Slug = "detektiv"
                        },
                        new
                        {
                            Id = 7,
                            Name = "детский",
                            Slug = "detskiy"
                        },
                        new
                        {
                            Id = 8,
                            Name = "для взрослых",
                            Slug = "dlya-vzroslyh"
                        },
                        new
                        {
                            Id = 9,
                            Name = "документальный",
                            Slug = "dokumentalnyy"
                        },
                        new
                        {
                            Id = 10,
                            Name = "драма",
                            Slug = "drama"
                        },
                        new
                        {
                            Id = 11,
                            Name = "игра",
                            Slug = "igra"
                        },
                        new
                        {
                            Id = 12,
                            Name = "история",
                            Slug = "istoriya"
                        },
                        new
                        {
                            Id = 13,
                            Name = "комедия",
                            Slug = "komediya"
                        },
                        new
                        {
                            Id = 14,
                            Name = "концерт",
                            Slug = "koncert"
                        },
                        new
                        {
                            Id = 15,
                            Name = "короткометражка",
                            Slug = "korotkometrazhka"
                        },
                        new
                        {
                            Id = 16,
                            Name = "криминал",
                            Slug = "kriminal"
                        },
                        new
                        {
                            Id = 17,
                            Name = "мелодрама",
                            Slug = "melodrama"
                        },
                        new
                        {
                            Id = 18,
                            Name = "музыка",
                            Slug = "muzyka"
                        },
                        new
                        {
                            Id = 19,
                            Name = "мультфильм",
                            Slug = "multfilm"
                        },
                        new
                        {
                            Id = 20,
                            Name = "мюзикл",
                            Slug = "myuzikl"
                        },
                        new
                        {
                            Id = 21,
                            Name = "новости",
                            Slug = "novosti"
                        },
                        new
                        {
                            Id = 22,
                            Name = "приключения",
                            Slug = "priklyucheniya"
                        },
                        new
                        {
                            Id = 23,
                            Name = "реальное ТВ",
                            Slug = "realnoe-TV"
                        },
                        new
                        {
                            Id = 24,
                            Name = "семейный",
                            Slug = "semeynyy"
                        },
                        new
                        {
                            Id = 25,
                            Name = "спорт",
                            Slug = "sport"
                        },
                        new
                        {
                            Id = 26,
                            Name = "ток-шоу",
                            Slug = "tok-shou"
                        },
                        new
                        {
                            Id = 27,
                            Name = "триллер",
                            Slug = "triller"
                        },
                        new
                        {
                            Id = 28,
                            Name = "ужасы",
                            Slug = "uzhasy"
                        },
                        new
                        {
                            Id = 29,
                            Name = "фантастика",
                            Slug = "fantastika"
                        },
                        new
                        {
                            Id = 30,
                            Name = "фильм-нуар",
                            Slug = "film-nuar"
                        },
                        new
                        {
                            Id = 31,
                            Name = "фэнтези",
                            Slug = "fentezi"
                        },
                        new
                        {
                            Id = 32,
                            Name = "церемония",
                            Slug = "ceremoniya"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.BusinessLogic.GenreMovieInfo", b =>
                {
                    b.Property<int>("MovieInfoId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("MovieInfoId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("GenreMovieInfo");
                });

            modelBuilder.Entity("DataAccess.Entities.BusinessLogic.MovieInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgeRating")
                        .HasColumnType("int");

                    b.Property<int?>("BudgetId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FeesId")
                        .HasColumnType("int");

                    b.Property<int>("MovieLength")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosterURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slogan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FeesId");

                    b.HasIndex("TypeId");

                    b.ToTable("Movies", t =>
                        {
                            t.HasCheckConstraint("CK_MovieInfo_MovieLength", "MovieLength > 0");

                            t.HasCheckConstraint("CK_MovieInfo_Rating", "0 <= Rating AND Rating <= 10");

                            t.HasCheckConstraint("CK_MovieInfo_Year", "Year >= 1900");
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.BusinessLogic.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("DataAccess.Entities.BusinessLogic.PersonProffessionInMovie", b =>
                {
                    b.Property<int>("MovieInfoId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("ProfessionId")
                        .HasColumnType("int");

                    b.HasKey("MovieInfoId", "PersonId", "ProfessionId");

                    b.HasIndex("PersonId");

                    b.HasIndex("ProfessionId");

                    b.ToTable("PersonProffessionInMovie");
                });

            modelBuilder.Entity("DataAccess.Entities.BusinessLogic.Profession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Professions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "актеры"
                        },
                        new
                        {
                            Id = 2,
                            Name = "актеры дубляжа"
                        },
                        new
                        {
                            Id = 3,
                            Name = "композиторы"
                        },
                        new
                        {
                            Id = 4,
                            Name = "монтажеры"
                        },
                        new
                        {
                            Id = 5,
                            Name = "операторы"
                        },
                        new
                        {
                            Id = 6,
                            Name = "продюсеры"
                        },
                        new
                        {
                            Id = 7,
                            Name = "редакторы"
                        },
                        new
                        {
                            Id = 8,
                            Name = "режиссеры"
                        },
                        new
                        {
                            Id = 9,
                            Name = "художники"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.BusinessLogic.SeasonsInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EpisodesCount")
                        .HasColumnType("int");

                    b.Property<int>("MovieInfoId")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieInfoId");

                    b.ToTable("SeasonsInfos", t =>
                        {
                            t.HasCheckConstraint("CK_SeasonsInfo_EpisodesCount", "EpisodesCount >= 0");

                            t.HasCheckConstraint("CK_SeasonsInfo_Number", "Number >= 0");
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.BusinessLogic.Types", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "animated-series",
                            Slug = "animated-series"
                        },
                        new
                        {
                            Id = 2,
                            Name = "anime",
                            Slug = "anime"
                        },
                        new
                        {
                            Id = 3,
                            Name = "cartoon",
                            Slug = "cartoon"
                        },
                        new
                        {
                            Id = 4,
                            Name = "mini-series",
                            Slug = "mini-series"
                        },
                        new
                        {
                            Id = 5,
                            Name = "movie",
                            Slug = "movie"
                        },
                        new
                        {
                            Id = 6,
                            Name = "tv-series",
                            Slug = "tv-series"
                        },
                        new
                        {
                            Id = 7,
                            Name = "tv-show",
                            Slug = "tv-show"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.IdentityLogic.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DataAccess.Entities.BusinessLogic.CountryMovieInfo", b =>
                {
                    b.HasOne("DataAccess.Entities.BusinessLogic.Country", "Country")
                        .WithMany("Movies")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.BusinessLogic.MovieInfo", null)
                        .WithMany("Countries")
                        .HasForeignKey("MovieInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("DataAccess.Entities.BusinessLogic.Fees", b =>
                {
                    b.HasOne("DataAccess.Entities.BusinessLogic.CurrencyValue", "Russia")
                        .WithMany()
                        .HasForeignKey("RussiaId");

                    b.HasOne("DataAccess.Entities.BusinessLogic.CurrencyValue", "USA")
                        .WithMany()
                        .HasForeignKey("USAId");

                    b.HasOne("DataAccess.Entities.BusinessLogic.CurrencyValue", "World")
                        .WithMany()
                        .HasForeignKey("WorldId");

                    b.Navigation("Russia");

                    b.Navigation("USA");

                    b.Navigation("World");
                });

            modelBuilder.Entity("DataAccess.Entities.BusinessLogic.GenreMovieInfo", b =>
                {
                    b.HasOne("DataAccess.Entities.BusinessLogic.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.BusinessLogic.MovieInfo", null)
                        .WithMany("Genres")
                        .HasForeignKey("MovieInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("DataAccess.Entities.BusinessLogic.MovieInfo", b =>
                {
                    b.HasOne("DataAccess.Entities.BusinessLogic.CurrencyValue", "Budget")
                        .WithMany()
                        .HasForeignKey("BudgetId");

                    b.HasOne("DataAccess.Entities.BusinessLogic.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("DataAccess.Entities.BusinessLogic.Fees", "Fees")
                        .WithMany()
                        .HasForeignKey("FeesId");

                    b.HasOne("DataAccess.Entities.BusinessLogic.Types", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Budget");

                    b.Navigation("Category");

                    b.Navigation("Fees");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("DataAccess.Entities.BusinessLogic.PersonProffessionInMovie", b =>
                {
                    b.HasOne("DataAccess.Entities.BusinessLogic.MovieInfo", null)
                        .WithMany("Proffessions")
                        .HasForeignKey("MovieInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.BusinessLogic.Person", "Person")
                        .WithMany("Proffessions")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.BusinessLogic.Profession", "Profession")
                        .WithMany()
                        .HasForeignKey("ProfessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Profession");
                });

            modelBuilder.Entity("DataAccess.Entities.BusinessLogic.SeasonsInfo", b =>
                {
                    b.HasOne("DataAccess.Entities.BusinessLogic.MovieInfo", "MovieInfo")
                        .WithMany("SeasonsInfo")
                        .HasForeignKey("MovieInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MovieInfo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DataAccess.Entities.IdentityLogic.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DataAccess.Entities.IdentityLogic.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.IdentityLogic.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DataAccess.Entities.IdentityLogic.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Entities.BusinessLogic.Country", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("DataAccess.Entities.BusinessLogic.Genre", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("DataAccess.Entities.BusinessLogic.MovieInfo", b =>
                {
                    b.Navigation("Countries");

                    b.Navigation("Genres");

                    b.Navigation("Proffessions");

                    b.Navigation("SeasonsInfo");
                });

            modelBuilder.Entity("DataAccess.Entities.BusinessLogic.Person", b =>
                {
                    b.Navigation("Proffessions");
                });
#pragma warning restore 612, 618
        }
    }
}
